name: ashisutanto

services:
  asterisk:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - asterisk-conf:/srv                  # Persistent storage
      - ./pulse:/run/pulse:rshared          # Use host audio
      - /etc/localtime:/etc/localtime:ro    # Use host timezone
      - ./asterisk-conf:/etc/asterisk       # Use host config
      - ./asterisk-logs:/var/log/asterisk   # Logs
      - ./asterisk-conf/resolv.conf:/etc/resolv.conf  # name servers

volumes:
  asterisk-conf:                            # Persistent storage
  