name: ashisutanto

services:
  asterisk:
    image: mlan/asterisk
    network_mode: host
    cap_add:
      - sys_ptrace                          # Only here to help testing
      - net_admin                           # Allow NFT, used by AutoBan
      - net_raw                             # Allow NFT, used by AutoBan
    environment:
      - SYSLOG_LEVEL=${SYSLOG_LEVEL-4}      # Logging
      - HOSTNAME=${ASTERISK_SRV-asterisk}.${DOMAIN-docker.localhost}
      - PULSE_SERVER=unix:/run/pulse/socket # Use host audio
      - PULSE_COOKIE=/run/pulse/cookie      # Use host audio
      - WEBSMSD_PORT=${WEBSMSD_PORT-80}     # WEBSMSD internal port
    volumes:
      - asterisk-conf:/srv                  # Persistent storage
      - ./pulse:/run/pulse:rshared          # Use host audio
      - /etc/localtime:/etc/localtime:ro    # Use host timezone
      - ./asterisk-conf:/etc/asterisk       # Use host config
      - ./asterisk-logs:/var/log/asterisk   # Logs
      - ./asterisk-conf/resolv.conf:/etc/resolv.conf  # name servers

volumes:
  asterisk-conf:                            # Persistent storage
  